# This workflow runs every five minutes to check for a new manifest
name: Check for new manifest
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'

      - name: yarn install
        uses: bahmutov/npm-install@v1.1.0

      - name: Check for manifest update
        run: yarn manifest:check
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          PAT: ${{ secrets.PAT }}
          SKIP_CHECK: 'false'

      - name: Check for new files
        id: data
        run: echo ::set-output name=porcelain::"$(git status --porcelain)"

      - name: Commit latest manifest version
        if: steps.data.outputs.porcelain
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: new manifest version
          commit_user_name: D2 Manifest Bot
          commit_user_email: destinyitemmanager@gmail.com
          commit_author: D2 Manifest Bot <destinyitemmanager@gmail.com>
